// Generated by `@winglibs/vite`. Do not edit.
/** Holds environment variables generated from Wing. */
interface WingEnv {
}
interface Wing { env: WingEnv; }
declare var wing: Wing;
interface Window {
	readonly wing: Wing;
}
