name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  TF_BACKEND_BUCKET_REGION: us-east-1
  PROJECT_PATH: ./ai-endpoints

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Winglang App
        uses: winglang/wing-github-action/actions/deploy@main
        with:
          entry: "main.w"
          target: "tf-aws"
          version: "latest"
          working-directory: ${{env.PROJECT_PATH}}
          backend: "s3"
        env:
          TF_BACKEND_BUCKET: ${{env.PROJECT_PATH}}
          TF_BACKEND_BUCKET_REGION: ${{ env.TF_BACKEND_BUCKET_REGION }}
          GEMINI_API: ${{ secrets.GEMINI }}
