name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  TF_BACKEND_BUCKET_REGION: us-east-1
  PROJECT_PATH: ./ai-endpoints
  S3_BUCKET_NAME: ai-endpoint-c85c1af5-20240226134657000700000001
  NODE_VERSION: 20

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Add .env file
        run: |
          cd ${{ env.PROJECT_PATH }}
          touch .env
          echo GEMINI_API=\"${{ secrets.GEMINI }}\" > .env
          ls -la
          cat .env

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        run: |
          cd ${{ env.PROJECT_PATH }}
          npm ci

      - name: Deploy Winglang App
        uses: winglang/wing-github-action/actions/deploy@main
        with:
          entry: "main.w"
          target: "tf-aws"
          version: "latest"
          working-directory: ${{env.PROJECT_PATH}}
          backend: "s3"
        env:
          TF_BACKEND_BUCKET: ${{env.S3_BUCKET_NAME}}
          TF_BACKEND_BUCKET_REGION: ${{ env.TF_BACKEND_BUCKET_REGION }}
